# -*- coding: utf-8 -*-
"""early_fire&smoke_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UkJRWDTODLYAcWVmMyl1_nJ_lryizjaT
"""

from google.colab import drive
drive.mount('/content/drive')

HOME = "/content/drive/MyDrive/YOLOv8-Fire-and-Smoke-Detection-main"

# Pip install method (recommended)

!pip install ultralytics==8.0.20

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

# Git clone method (for development)

# %cd {HOME}
# !git clone github.com/ultralytics/ultralytics
# %cd {HOME}/ultralytics
# !pip install -qe ultralytics

# from IPython import display
# display.clear_output()

# import ultralytics
# ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="Ztmd4vPhJsooT3pDfv4r")
project = rf.workspace("fyp-oyjrq").project("fire_detection_prediction")
dataset = project.version(1).download("yolov5")

"""## Custom Training"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=25 imgsz=800 plots=True

!ls {HOME}/runs/detect/train/

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/confusion_matrix.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/results.png', width=600)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'{HOME}/runs/detect/train/val_batch0_pred.jpg', width=600)

"""## Validate Custom Model"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=val model={HOME}/runs/detect/train/weights/best.pt data={dataset.location}/data.yaml

"""## Inference with Custom Model"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=predict model={HOME}/runs/detect/train/weights/best.pt conf=0.25 source={dataset.location}/test/images save=True

"""**NOTE:** Let's take a look at few results."""

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'{HOME}/runs/detect/predict/*.jpg')[:3]:
      display(Image(filename=image_path, width=600))
      print("\n")

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=predict model={HOME}/runs/detect/train/weights/best.pt conf=0.25 source=/content/drive/MyDrive/test.mp4 save=True

"""## Conclusion

Early fire detection  
This project  is inspired by 'Fire Fire everywhere, not a tree alive!'. This quote perfectly fits the Amazon rainforest fires, which became a global concern in 2019. It is crucial to prevent such forest fires if we wish to fight against climate change. And a solution for this can be provided by deep learning algorithms. One can use the RGB model of colors to identify fire and smoke regions in an image.

This tutorial walks you through how we can use yolov8 to fine tune the fire detection model.It can be trained with more different images as per the use case in order to get efficient result. Thanks for learning with me.Stay tune for next topic.
"""

